// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MoviesList.Model;
using System;

namespace MoviesList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180701183308_addUserConnectionstoDB")]
    partial class addUserConnectionstoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesList.Model.Movies+MovieData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MovieDirector");

                    b.Property<string>("MovieGenre");

                    b.Property<string>("MovieName");

                    b.Property<int>("MovieYear");

                    b.HasKey("ID");

                    b.ToTable("MovieDataItems");
                });
#pragma warning restore 612, 618
        }
    }
}
